// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "hal/hal.h"
#include "modules/CompassModule.h"
#include "modules/Ds1302Module.h"

static SystemModule _m_system;
static CompassModule _m_compass;
static Ds1302Module _m_ds1302(22, 19, 21);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    hal_i2c_init(6, 7, 100000);
    reg.registerModule(_m_compass);
    reg.registerModule(_m_ds1302);
    if (commander_on_ds1302_ready) commander_on_ds1302_ready(_m_ds1302);
}
