// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "platform/esp32/AiCamUartTransport.h"
#include "modules/aicam/AiCamModule.h"
#include "transport/uart/UartTransport.h"

static SystemModule _m_system;
static AiCamUartTransport _t_aicam(43, 44);
static AiCamModule _m_aicam(_t_aicam);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_aicam);
    if (commander_on_aicam_ready) commander_on_aicam_ready(_m_aicam);
}

extern "C" void commander_on_app_tickers(UartTransport &) __attribute__((weak));

extern "C" void commander_on_uart_ready(UartTransport &uart) {
    uart.addTicker(_m_aicam);
    if (commander_on_app_tickers) commander_on_app_tickers(uart);
}
