// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "hal/hal.h"
#include "modules/Ina219Module.h"

static SystemModule _m_system;
static Ina219Module _m_ina219;

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    hal_i2c_init(8, 9, 100000);
    _m_ina219.addChannel("a", 0x40);
    reg.registerModule(_m_ina219);
}
