// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "modules/Ds1302Module.h"
#include "platform/esp32/IpstubeModule.h"
#include "platform/esp32/Ws2812Module.h"

static SystemModule _m_system;
static Ds1302Module _m_ds1302(22, 19, 21);
static IpstubeModule _m_ipstube;
void commander_on_ipstube_ready(IpstubeModule &);
static Ws2812Module _m_ws2812(5, 6, Ws2812Module::GRB);
void commander_on_ws2812_ready(Ws2812Module &);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_ds1302);
    if (commander_on_ds1302_ready) commander_on_ds1302_ready(_m_ds1302);
    reg.registerModule(_m_ipstube);
    commander_on_ipstube_ready(_m_ipstube);
    reg.registerModule(_m_ws2812);
    commander_on_ws2812_ready(_m_ws2812);
}
