// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "hal/hal.h"
#include "modules/CompassModule.h"
#include "modules/I2CDiagModule.h"
#include "modules/locomotion/LocomotionModule.h"

static SystemModule _m_system;
static CompassModule _m_compass;
static I2CDiagModule _m_i2c;
static LocomotionModule _m_locomotion(66);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    hal_i2c_init(6, 7, 100000);
    reg.registerModule(_m_compass);
    reg.registerModule(_m_i2c);
    reg.registerModule(_m_locomotion);
}
