// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "modules/display/St7789Module.h"

static SystemModule _m_system;
static const SpiPanelConfig _c_st7789 = [] {
    SpiPanelConfig c;
    c.bus = 1; c.sck = 10; c.mosi = 11;
    c.cs = 9; c.dc = 8; c.rst = 12; c.bl = 25;
    c.nativeW = 135; c.nativeH = 240;
    c.ramW = 240; c.ramH = 320;
    c.rotation = 1; c.hz = 40000000; c.invert = true;
    return c;
}();
static St7789Module _m_st7789(_c_st7789);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_st7789);
    if (commander_on_display_ready) commander_on_display_ready(_m_st7789);
}
