// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "modules/BuzzerModule.h"
#include "transport/uart/UartTransport.h"

static SystemModule _m_system;
static BuzzerModule _m_buzzer(13);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_buzzer);
    _m_buzzer.setVolume(0);
    if (commander_on_buzzer_ready) commander_on_buzzer_ready(_m_buzzer);
}

extern "C" void commander_on_app_tickers(UartTransport &) __attribute__((weak));

extern "C" void commander_on_uart_ready(UartTransport &uart) {
    uart.addTicker(_m_buzzer);
    if (commander_on_app_tickers) commander_on_app_tickers(uart);
}
