// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "platform/pico/PicoBluepadBackend.h"

static SystemModule _m_system;
static PicoBluepadBackend _m_controller_backend;
static ControllerModule _m_controller(_m_controller_backend);
void commander_on_controller_ready(ControllerModule &);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_controller);
    commander_on_controller_ready(_m_controller);
}
