// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "modules/input/ButtonsModule.h"
#include "modules/BuzzerModule.h"
#include "hal/hal.h"
#include "modules/touch/Gt911Module.h"
#include "modules/input/JoystickModule.h"
#include "modules/LedModule.h"
#include "modules/display/St7796Module.h"
#include "modules/WifiModule.h"
#include "platform/pico/PicoWs2812Module.h"
#include "transport/uart/UartTransport.h"

static SystemModule _m_system;
static const uint8_t _p_buttons[] = {15, 14};
static ButtonsModule _m_buttons(_p_buttons, 2, true, 25);
static BuzzerModule _m_buzzer(13);
static Gt911Module _m_gt911(0x5D, 0);
static JoystickModule _m_joystick(26, 27, -1, 30);
static const uint8_t _p_leds[] = {16, 17};
static LedModule _m_leds(_p_leds, 2, true);
static const SpiPanelConfig _c_st7796 = [] {
    SpiPanelConfig c;
    c.bus = 0; c.sck = 2; c.mosi = 3;
    c.cs = 5; c.dc = 6; c.rst = 7; c.bl = -1;
    c.nativeW = 320; c.nativeH = 480;
    c.ramW = 0; c.ramH = 0;
    c.rotation = 0; c.hz = 40000000; c.invert = true;
    return c;
}();
static St7796Module _m_st7796(_c_st7796);
static WifiModule _m_wifi;
static PicoWs2812Module _m_ws2812(12, 1, PicoWs2812Module::GRB);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_buttons);
    if (commander_on_buttons_ready) commander_on_buttons_ready(_m_buttons);
    reg.registerModule(_m_buzzer);
    if (commander_on_buzzer_ready) commander_on_buzzer_ready(_m_buzzer);
    hal_i2c_init(8, 9, 100000);
    reg.registerModule(_m_gt911);
    if (commander_on_touch_ready) commander_on_touch_ready(_m_gt911);
    reg.registerModule(_m_joystick);
    if (commander_on_joystick_ready) commander_on_joystick_ready(_m_joystick);
    reg.registerModule(_m_leds);
    if (commander_on_leds_ready) commander_on_leds_ready(_m_leds);
    reg.registerModule(_m_st7796);
    if (commander_on_display_ready) commander_on_display_ready(_m_st7796);
    reg.registerModule(_m_wifi);
    reg.registerModule(_m_ws2812);
    if (commander_on_ws2812_ready) commander_on_ws2812_ready(_m_ws2812);
}

extern "C" void commander_on_app_tickers(UartTransport &) __attribute__((weak));

extern "C" void commander_on_uart_ready(UartTransport &uart) {
    uart.addTicker(_m_buttons);
    uart.addTicker(_m_buzzer);
    uart.addTicker(_m_gt911);
    uart.addTicker(_m_joystick);
    uart.addTicker(_m_leds);
    if (commander_on_app_tickers) commander_on_app_tickers(uart);
}
