// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "platform/pico/PicoWs2812Module.h"

static SystemModule _m_system;
static PicoWs2812Module _m_ws2812(12, 1, PicoWs2812Module::GRB);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_ws2812);
    _m_ws2812.setBrightness(10);
    if (commander_on_ws2812_ready) commander_on_ws2812_ready(_m_ws2812);
}
