// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "runners/pico/SerialMonitorModule.h"

static SystemModule _m_system;
static SerialMonitorModule _m_serial_monitor(uart1, 9, 8, 115200);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_serial_monitor);
}
