// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"

static SystemModule _m_system;

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
}
