// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include <Arduino.h>
#include "modules/roomba/RoombaModule.h"

static SystemModule _m_system;
class R4RoombaPort : public RoombaPort {
public:
    void begin(long baud, int brcPin = -1) {
        _brc = brcPin;
        Serial1.begin(baud);
        if (_brc >= 0) { pinMode(_brc, OUTPUT); digitalWrite(_brc, HIGH); }
    }
    void     write(const uint8_t *d, size_t n) override { Serial1.write(d, n); }
    int      read() override       { return Serial1.read(); }
    int      available() override  { return Serial1.available(); }
    uint32_t now_ms() override     { return millis(); }
    void     delay_ms(uint32_t ms) override { delay(ms); }
    bool     has_brc() const override { return _brc >= 0; }
    void     set_brc(bool high) override { if (_brc >= 0) digitalWrite(_brc, high ? HIGH : LOW); }
private:
    int _brc = -1;
};
static R4RoombaPort _m_roomba_port;
static RoombaModule _m_roomba(_m_roomba_port);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    _m_roomba_port.begin(115200, -1);
    reg.registerModule(_m_roomba);
}
