// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "platform/arduino/IRModule.h"
#include "platform/arduino/IRModule.cpp"
#include "modules/WifiModule.h"
#include "transport/uart/UartTransport.h"

static SystemModule _m_system;
static IRModule _m_ir(5);
static WifiModule _m_wifi;

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_ir);
    reg.registerModule(_m_wifi);
}

extern "C" void commander_on_app_tickers(UartTransport &) __attribute__((weak));

extern "C" void commander_on_uart_ready(UartTransport &uart) {
    uart.addTicker(_m_ir);
    if (commander_on_app_tickers) commander_on_app_tickers(uart);
}
