// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "hal/hal.h"
#include "modules/CompassModule.h"
#include "modules/SonarModule.h"

static SystemModule _m_system;
static CompassModule _m_compass;
static SonarModule _m_sonar(6);

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    hal_i2c_init(4, 5, 100000);
    reg.registerModule(_m_compass);
    reg.registerModule(_m_sonar);
}
