// AUTO-GENERATED by cmdr — do not edit.
// Manage modules with: cmdr module enable|disable|list
#pragma once
#include "core/CommandRegistry.h"
#include "core/SystemModule.h"
#include "platform/zephyr/ZephyrIRModule.h"
#include "transport/channels/ChannelBusRunner.h"

static SystemModule _m_system;
static ZephyrIRModule _m_ir;
static ChannelTransport::ChannelPublisher _pub_ir;

inline void commander_register_modules(CommandRegistry &reg) {
    reg.registerModule(_m_system);
    reg.registerModule(_m_ir);
}

extern "C" void commander_on_channel_bus_ready(ChannelBusRunner &bus) {
    _pub_ir = bus.channels().publisher(1);
    _m_ir.setOutput(&_pub_ir);
    bus.addTicker(_m_ir);
}
