"""Invariant lint over generated commander_modules.h — rules that must hold for
*every* (target, module-set), enforced by a test rather than a code reviewer.

These pin the codegen-regression class from the docs/testing.md bug table:
  • duplicate include  → assert includes are unique
  • no designated initializers (all toolchains default to C++17; AVR/old GCC choke)
  • dedup of shared bring-up lines (two I2C modules → one hal_i2c_init)
  • the ticker-hook ↔ register-hook structure is well-formed and bus-correct
"""
import re

import pytest

from conftest import build_modules
from test_codegen_golden import MATRIX


def _emit(cli, case, tmp_path):
    target, label, names, overrides = case
    modules = build_modules(target, names, overrides)
    out = tmp_path / "commander_modules.h"
    cli.generate_modules_file(target, modules, out)
    return target, out.read_text()


IDS = [f"{c[0]}-{c[1]}" for c in MATRIX]


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_banner_and_pragma(case, cli_mod, tmp_path):
    _t, text = _emit(cli_mod, case, tmp_path)
    lines = text.splitlines()
    assert lines[0].startswith("// AUTO-GENERATED by cmdr"), "must carry the do-not-edit banner"
    assert "#pragma once" in lines[:5], "header needs an early #pragma once"
    assert '#include "core/CommandRegistry.h"' in text


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_includes_are_unique(case, cli_mod, tmp_path):
    """The exact duplicate-include bug this suite exists to catch."""
    _t, text = _emit(cli_mod, case, tmp_path)
    includes = [ln for ln in text.splitlines() if ln.startswith("#include")]
    assert len(includes) == len(set(includes)), f"duplicate #include emitted: {includes}"


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_no_designated_initializers(case, cli_mod, tmp_path):
    """C++17 (and AVR GCC) reject C99 designated initializers; generated code must
    use positional/explicit construction. Flags `{ .field = ... }`."""
    _t, text = _emit(cli_mod, case, tmp_path)
    bad = re.findall(r"\{\s*\.\w+\s*=", text)
    assert not bad, f"designated initializer in generated code: {bad}"


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_balanced_braces_and_parens(case, cli_mod, tmp_path):
    _t, text = _emit(cli_mod, case, tmp_path)
    assert text.count("{") == text.count("}"), "unbalanced braces"
    assert text.count("(") == text.count(")"), "unbalanced parens"


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_system_is_first(case, cli_mod, tmp_path):
    """system is always-on and must be declared + registered before anything else."""
    _t, text = _emit(cli_mod, case, tmp_path)
    assert "static SystemModule _m_system;" in text
    reg_body = text.split("commander_register_modules", 1)[1]
    first_reg = re.search(r"reg\.registerModule\((_m_\w+)\)", reg_body)
    assert first_reg and first_reg.group(1) == "_m_system", "system must register first"


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_register_lines_deduped(case, cli_mod, tmp_path):
    """Identical register/bring-up lines are collapsed (the shared-HAL-bus dedup)."""
    _t, text = _emit(cli_mod, case, tmp_path)
    body = text.split("commander_register_modules", 1)[1].split("}", 1)[0]
    reg_lines = [ln.strip() for ln in body.splitlines() if ln.strip()]
    assert len(reg_lines) == len(set(reg_lines)), f"duplicate register line: {reg_lines}"


def test_i2c_dedup_concrete(cli_mod, tmp_path):
    """Three I2C modules at the same pins emit exactly one hal_i2c_init."""
    modules = build_modules("pico", ["compass", "i2c", "locomotion"])
    out = tmp_path / "commander_modules.h"
    cli_mod.generate_modules_file("pico", modules, out)
    text = out.read_text()
    assert text.count("hal_i2c_init(") == 1, "shared I2C bring-up should be deduped to one call"


@pytest.mark.parametrize("case", MATRIX, ids=IDS)
def test_ticker_hook_matches_build(case, cli_mod, tmp_path):
    """If a module needs ticking, the right hook is emitted: the unoq channel-bus
    build uses commander_on_channel_bus_ready (bus in scope); everyone else
    commander_on_uart_ready. addTicker must live inside that hook, not the registrar."""
    target, text = _emit(cli_mod, case, tmp_path)
    if "addTicker" not in text:
        # No tickers: no ticker hook should be emitted either.
        assert "commander_on_uart_ready" not in text
        assert "commander_on_channel_bus_ready" not in text
        return
    if target == "unoq":
        assert "commander_on_channel_bus_ready(ChannelBusRunner &bus)" in text
        assert "commander_on_uart_ready" not in text
    else:
        assert "commander_on_uart_ready(UartTransport &uart)" in text
        assert "commander_on_channel_bus_ready" not in text
    # addTicker only appears after the hook opens, never inside register_modules.
    reg_body = text.split("commander_register_modules", 1)[1].split("}", 1)[0]
    assert "addTicker" not in reg_body, "addTicker must be in the ticker hook, not the registrar"
