#!/usr/bin/env python3
"""Convert an image to an RGB565 C header for the ipstube display driver.

The output is a `static const uint16_t <name>[W*H]` array (plus <name>_width /
<name>_height) in natural little-endian RGB565 — exactly what
IpstubeModule::drawBitmap() expects (the ST7789 is configured data_endian=LITTLE,
so no byte-swapping). A flash `const` array can be passed straight to drawBitmap;
the SPI driver bounces it to DMA memory for you.

    pip install pillow
    img2rgb565.py photo.png -o main/clockface.h --name clockface
    # then in the app:  #include "clockface.h"
    #                   disp.drawBitmap(IpstubeModule::kAll, clockface);

Default size is one IPSTube panel (135x240). --fit cover (default) fills the
panel and centre-crops; contain letterboxes (black); stretch ignores aspect.
"""
import argparse
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow not installed — run: pip install pillow")


def fit_image(img, w, h, mode):
    if img.mode in ("RGBA", "LA", "PA") or (img.mode == "P" and "transparency" in img.info):
        img = img.convert("RGBA")
        img = Image.alpha_composite(Image.new("RGBA", img.size, (0, 0, 0, 255)), img)
    img = img.convert("RGB")
    if mode == "stretch":
        return img.resize((w, h), Image.LANCZOS)
    sw, sh = img.size
    scale = (max(w / sw, h / sh) if mode == "cover" else min(w / sw, h / sh))
    img = img.resize((max(1, round(sw * scale)), max(1, round(sh * scale))), Image.LANCZOS)
    canvas = Image.new("RGB", (w, h), (0, 0, 0))
    iw, ih = img.size
    off = ((w - iw) // 2, (h - ih) // 2)
    if mode == "cover":
        img = img.crop((-off[0], -off[1], -off[0] + w, -off[1] + h))
        canvas.paste(img, (0, 0))
    else:  # contain
        canvas.paste(img, off)
    return canvas


def to_rgb565(img):
    data = img.tobytes()  # row-major RGB, 3 bytes/pixel — stable across Pillow versions
    return [((data[i] & 0xF8) << 8) | ((data[i + 1] & 0xFC) << 3) | (data[i + 2] >> 3)
            for i in range(0, len(data), 3)]


def main():
    ap = argparse.ArgumentParser(description="Image -> RGB565 C header for ipstube")
    ap.add_argument("image")
    ap.add_argument("-o", "--output", help="output .h (default: stdout)")
    ap.add_argument("--name", default="image", help="C identifier (default: image)")
    ap.add_argument("--width", type=int, default=135)
    ap.add_argument("--height", type=int, default=240)
    ap.add_argument("--fit", choices=["cover", "contain", "stretch"], default="cover")
    args = ap.parse_args()

    img = fit_image(Image.open(args.image), args.width, args.height, args.fit)
    px = to_rgb565(img)

    lines = [
        f"// Generated by img2rgb565.py from {args.image} ({args.width}x{args.height}, {args.fit})",
        "#pragma once",
        "#include <stdint.h>",
        f"static const int {args.name}_width  = {args.width};",
        f"static const int {args.name}_height = {args.height};",
        f"static const uint16_t {args.name}[{args.width} * {args.height}] = {{",
    ]
    for i in range(0, len(px), 12):
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in px[i:i + 12]) + ",")
    lines.append("};")
    text = "\n".join(lines) + "\n"

    if args.output:
        with open(args.output, "w") as f:
            f.write(text)
        print(f"wrote {args.output}  ({args.width}x{args.height}, {len(px)} px, "
              f"{len(px) * 2} bytes)", file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
